### ISSUE TITLE
Missing required option :name is not descriptive

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/registration-app#116]
```ruby
ArgumentError: missing required option :name
/Users/kyle/Documents/ctf/registration-app/lib/vpn_module.rb:19:in `initialize'
/Users/kyle/Documents/ctf/registration-app/config/initializers/s3_initializer.rb:3:in `<top (required)>'
/Users/kyle/Documents/ctf/registration-app/config/environment.rb:7:in `<top (required)>'
bin/rails:6:in `require'
bin/rails:6:in `<main>'
Tasks: TOP => db:schema:load => environment
(See full trace by running task with --trace)
```

The solution is to source the `.dev_vars`. Should be more descriptive.

**Comment by noraj1337** [comment]
@Bialogs I can't find any info about `.dev_vars` what is that file ?

**Comment by noraj1337** [comment]
It seems that's the error occurs with `aws-sdk-s3` but why this gem is required ? I should be able to install the ctf scoreboard somewhere else than AWS. I can't build the app because `.dev_vars` is not created, but I don't want to host the ctf on AWS.

```
$ bundle exec rake db:schema:load
rake aborted!
ArgumentError: missing required option :name
/home/shark/.rvm/gems/ruby-2.3.5/gems/aws-sdk-s3-1.4.0/lib/aws-sdk-s3/bucket.rb:658:in `extract_name'
/home/shark/.rvm/gems/ruby-2.3.5/gems/aws-sdk-s3-1.4.0/lib/aws-sdk-s3/bucket.rb:21:in `initialize'
/home/shark/.rvm/gems/ruby-2.3.5/gems/aws-sdk-s3-1.4.0/lib/aws-sdk-s3/resource.rb:69:in `new'
/home/shark/.rvm/gems/ruby-2.3.5/gems/aws-sdk-s3-1.4.0/lib/aws-sdk-s3/resource.rb:69:in `bucket'
/home/shark/Dev/registration-app/lib/vpn_module.rb:19:in `initialize'
/home/shark/Dev/registration-app/config/initializers/s3_initializer.rb:3:in `<top (required)>'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/home/shark/Dev/registration-app/config/environment.rb:7:in `<top (required)>'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/shark/.rvm/gems/ruby-2.3.5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/home/shark/.rvm/gems/ruby-2.3.5/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/shark/.rvm/gems/ruby-2.3.5/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home/shark/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
/home/shark/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load => environment
(See full trace by running task with --trace)
```

**Comment by rbclark** [comment]
This does not mean it has to be installed on AWS, it just means that if you want the VPN certificate syncing functionality that we use then you need to include S3 credentials. I will have a fix released in the next few hours.

**Comment by noraj1337** [comment]
@rbclark thx PR worked
